title: <p align="center"> Kiet Nguyen </p>

logo: "/images/profile.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf" target="_blank">Resume</a> |
  <a href="mailto:kietng.work@email.com">Email</a> |
  <a href="https://www.linkedin.com/in/kietn1/" target="_blank" rel="noopener noreferrer">LinkedIn</a> |
  <a href="https://github.com/kietngwork" target="_blank" rel="noopener noreferrer">GitHub</a>

  </p>
  
  <p align="justify">
 I hold an MS degree in Business Analytics from California State Polytechnic University, Pomona, and Iâ€™m looking for a full-time role where I can use data and analytical tools to uncover insights, support better decisions, and drive meaningful impact across marketing, banking, and finance.
  <br><br>
  
   </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
